### PR TITLE
Reverted changes to ReadME

### PR DESCRIPTION
**Pull request by AvijitGhosh82**
Merge it now ...

### CODE REVIEW

**Comment by OrkoHunter** [comment]
Hey @AvijitGhosh82, somehow there are merge conflicts in this PR. Do you know how to solve them? It's a little bit tricky. There is no option to merge this PR unless the conflict is resolved. So, we have two options now
1) Learn how to update/rebase your master against the upstream and solve the merge conflicts. (Very tricky, I think you should try this after next session)

Or

2) Delete your repository from github. Fork again, clone it. Add file, commit and push. (Recommended and easy)

Your call.

**Comment by AvijitGhosh82** [comment]
It is probably fixed now, try to pull again..

**Comment by kshitij10496** [comment]
@AvijitGhosh82 I think you should write a new file and push it to the PR.

**Comment by kshitij10496** [comment]
@AvijitGhosh82 We should discuss about the PR here itself.

Ping @OrkoHunter

**Comment by OrkoHunter** [comment]
This PR is merged. You may wish to add a new file and create a new PR. That's still pending.

**Pull request merged**
