### PR TITLE
Adding new file

### PR DESCRIPTION
**Pull request by AakashSingh01**
added Aakash Singh.md

### CODE REVIEW

**Comment by kshitij10496** [comment]
@AakashSingh01 Write better messages.

**Comment by OrkoHunter** [comment]
I guess it's good now.
@AakashSingh01 Did you use `amend` ? Or just a single commit?

**Comment by kshitij10496** [comment]
@OrkoHunter Are we merging this ?

**Comment by OrkoHunter** [comment]
Sure!

**Pull request merged**
