### PR TITLE
first

### PR DESCRIPTION
**Pull request by rava-dosa**
Add Apoorva Kumar ([rava-dosa](https://github.com/rava-dosa)) | apoorvakumar169@gmail.com

### CODE REVIEW

**Comment by rava-dosa** [comment]
I tried to merge in git master & branch "trying" & terminal is giving everything is up to date

**Comment by madan96** [comment]
Hints: See what is
git commit --amend
git reset --hard HEAD~ Be very careful with this though
git fetch upstream
git merge


Hope to see you finish this PR soon. :)

**Comment by rava-dosa** [comment]
remote: Permission to kossiitkgp/git-sandbox.git denied to rava-dosa.
fatal: unable to access 'https://github.com/kossiitkgp/git-sandbox.git/': The requested URL returned error: 403

**Comment by rava-dosa** [comment]
how to remove this ?

**Pull request closed without merging**
